=== ansango/GFGS-DAM/06. Lenguajes de Marcas/PACS/UF1_PAC2/M04_UF1_PAC02/Ejercicio3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="tiket">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos_tiket"/>
        <xs:element ref="datos_comercio"/>
        <xs:element ref="datos_compra"/>
      </xs:sequence>
      <xs:attribute name="codigo" type="xs:ID" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="datos_tiket">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fecha"/>
        <xs:element ref="hora"/>
        <xs:element ref="precio_total"/>
        <xs:element ref="forma_pago"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="datos_comercio">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="direccion"/>
        <xs:element ref="cif"/>
        <xs:element ref="telefono"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="datos_compra">
    <xs:complexType>
        <xs:sequence>
          <xs:element ref="lineas_compra"/>
        </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="fecha" type="xs:date"/>

  <xs:element name="hora" type="xs:time"/>

  <xs:element name="precio_total">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cantidad_sin_iva"/>
        <xs:element ref="cantidad_iva"/>
        <xs:element ref="cantidad_con_iva"/>
      </xs:sequence>
      <xs:attribute name="moneda" type="xs:NMTOKEN" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="forma_pago">
    <xs:complexType>
      <xs:choice>
        <xs:element ref="tarjeta"/>
        <xs:element ref="efectivo"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <xs:element name="cantidad_sin_iva" type="xs:double"/>

  <xs:element name="cantidad_iva" type="xs:double"/>

  <xs:element name="cantidad_con_iva" type="xs:double"/>

  <xs:element name="efectivo">
    <xs:complexType/>
  </xs:element>
  
    <xs:element name="tarjeta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="cliente"/>
      </xs:sequence>
        <xs:attribute name="tipo" type="xs:string" use="required"/>
        <xs:attribute name="numero" use="required">
          <xs:simpleType>
              <xs:restriction base="xs:string">
                  <xs:pattern value="\*{12}\d{4}"/>
              </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="cliente" type="xs:string"/>

  <xs:element name="nombre" type="xs:string"/>

  <xs:element name="direccion" type="xs:string"/>

  <xs:element name="cif" type="xs:string"/>

  <xs:element name="telefono" type="xs:string"/>

  <xs:element name="lineas_compra">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre_articulo"/>
        <xs:element ref="cantidad"/>
        <xs:element ref="precio_und_sin_iva"/>
        <xs:element ref="iva"/>
        <xs:element ref="pvp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="nombre_articulo" type="xs:string"/>

  <xs:element name="cantidad" type="xs:int"/>

  <xs:element name="precio_und_sin_iva" type="xs:double"/>

  <xs:element name="iva" type="xs:double"/>

  <xs:element name="pvp" type="xs:double"/>
  
  

</xs:schema>

=== ansango/GFGS-DAM/06. Lenguajes de Marcas/PACS/UF1_PAC2/M04_UF1_PAC02/Ejercicio1.xml
<?xml version="1.0"?>
<!--Ejercicio 1 Pag 258-->
<!--DOCTYPE tiket SYSTEM "Ejercicio2.dtd"-->
<tiket xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Ejercicio3.xsd" codigo="t00040">
  <datos_tiket>
      <fecha>2015-10-15</fecha>
      <hora>16:00:00</hora>
      <precio_total moneda="euro">
          <cantidad_sin_iva>25.20</cantidad_sin_iva>
          <cantidad_iva>5.30</cantidad_iva>
          <cantidad_con_iva>30.50</cantidad_con_iva>
      </precio_total>
      <forma_pago>
          <tarjeta tipo="Visa" numero="************1234">
              <cliente>Pedro Gomez</cliente>
          </tarjeta>
      </forma_pago>
  </datos_tiket>
  <datos_comercio>
    <nombre>Mercadona</nombre>
    <direccion>C/ El alto, 32</direccion>
    <cif>A-12458789M</cif>
    <telefono>914569632</telefono>
  </datos_comercio>
  <datos_compra>
      <lineas_compra>
          <nombre_articulo>Entrecot</nombre_articulo>
          <cantidad>4</cantidad>
          <precio_und_sin_iva>6.30</precio_und_sin_iva>
          <iva>1.32</iva>
          <pvp>7.62</pvp>
      </lineas_compra>
  </datos_compra>
</tiket>
